//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoice_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblinvoice_details()
        {
            this.tblinvoice_product = new HashSet<tblinvoice_product>();
            this.tblinvoice_payment = new HashSet<tblinvoice_payment>();
        }
    
        public int invoice_id { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<double> total_ammount { get; set; }
    
        public virtual tblcutomer tblcutomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_product> tblinvoice_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_payment> tblinvoice_payment { get; set; }
    }
}
