//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoice_payment
    {
        public int payment_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<double> payment_ammount { get; set; }
        public string payment_mode { get; set; }
        public string description { get; set; }
    
        public virtual tblinvoice_details tblinvoice_details { get; set; }
    }
}
