//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblproduct()
        {
            this.tblinvoices = new HashSet<tblinvoice>();
            this.tblinvoice_product = new HashSet<tblinvoice_product>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<int> stock_quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice> tblinvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_product> tblinvoice_product { get; set; }
    }
}
